# Generated by Django 5.2.9 on 2026-03-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressApp', '0002_progressdb_alter_workoutlog_progress_delete_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressdb',
            name='arms',
        ),
        migrations.RemoveField(
            model_name='progressdb',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='progressdb',
            name='thigh',
        ),
        migrations.RemoveField(
            model_name='progressdb',
            name='waist',
        ),
    ]
