# Generated by Django 5.2.9 on 2026-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressApp', '0003_remove_progressdb_arms_remove_progressdb_chest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
