# Generated by Django 5.2.9 on 2026-04-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressApp', '0006_alter_workoutlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='date_logged',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
