# Generated by Django 5.2.9 on 2026-04-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressApp', '0007_remove_workoutlog_date_logged_workoutlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='date',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
