# Generated by Django 5.2.9 on 2026-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Name', models.CharField(max_length=100)),
                ('M_Image', models.ImageField(upload_to='Muscle Groups')),
            ],
        ),
    ]
