# Generated by Django 5.2.9 on 2026-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Muscle_Group', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Video', models.FileField(upload_to='Workout Videos')),
            ],
        ),
    ]
