# Generated by Django 5.2.9 on 2026-02-24 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('Height', models.FloatField(help_text='Height in cm')),
                ('Weight', models.FloatField(help_text='Weight in kg')),
                ('Target_weight', models.FloatField(blank=True, null=True)),
                ('Goal', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20)),
                ('Activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active')], max_length=20)),
                ('Experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
