# Generated by Django 5.2.9 on 2026-02-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_userdb_profiledb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledb',
            old_name='User',
            new_name='user',
        ),
    ]
