# Generated by Django 5.2.9 on 2026-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_user_profiledb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='Name',
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Goal',
            field=models.CharField(blank=True, choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='Weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
