# Generated by Django 5.2.9 on 2026-03-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_profiledb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiledb',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
