# Generated by Django 5.2.9 on 2026-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_profiledb_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledb',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
