# Generated by Django 5.2.9 on 2026-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_profiledb_subscription_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
